version: "2.4"

services:
  client:
    image: "jethred/multi-client"
    mem_limit: 128m
    restart: unless-stopped
    networks:
      - vnet

  api:
    image: "jethred/multi-server"
    mem_limit: 128m
    restart: unless-stopped
    networks: 
      - vnet

  worker:
    image: "jethred/multi-worker"
    mem_limit: 128m

  nginx:
    image: "jethred/multi-nginx"
    restart: unless-stopped
    ports: 
      - "80:80"
    networks:
      - vnet

networks:
  vnet:    


  

    