version: "2.4"

services:
  client:
    image: "jethred/multi-client"
    mem_limit: 128m
    restart: unless-stopped

  api:
    image: "jethred/multi-server"
    mem_limit: 128m
    restart: unless-stopped

  worker:
    image: "jethred/multi-worker"
    mem_limit: 128m

  nginx:
    image: "jethred/multi-nginx"
    mem_limit: 128m
    ports:
      - '8080:8080'
    restart: unless-stopped
    