version: "2.4"

services:
  client:
    image: "jethred/multi-client"
    mem_limit: 128m
    command: ["bash", "-c", "/etc/init.d/nginx start || echo 'nginx started with errors'"]
    depends_on:
      - api
    restart: always
    networks:
      - vnet

  api:
    image: "jethred/multi-server"
    mem_limit: 128m
    networks:
      - vnet

  worker:
    image: "jethred/multi-worker"
    mem_limit: 128m

  nginx:
    image: "jethred/multi-nginx"
    mem_limit: 128m
    restart: always
    ports:
      - '80:80'
    command: ["bash", "-c", "/etc/init.d/nginx start || echo 'nginx started with errors'"]
    depends_on:
      - api
      - client
    networks:
      - vnet

networks:
  vnet:
    